version: '3.9'


services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    
  client:
    build: ./client
    ports:
      - 8011:8011
    environment:
      - ENV=prod
    depends_on:
      - backend
    